# Inspired by https://github.com/stboch/homeassistant-blueprints/blob/203573805074ce9b5454a5e74d17c68c50573cf6/mobile_app_android_alarm.yaml
blueprint:
  name: Select 
  description: Set an alarm with help of the homeassistant companion app
  domain: script
  source_url: https://github.com/YoshiiPlayzz/homeassistant-extras/blob/main/blueprints/companion-android-select-device.yaml
  input:
    notify_device:
      name: Device to set the alarm to
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector: 
        action:
mode: restart
sequence:
  - service: !input notify_device
    message: "Test"
          