# Inspired by https://github.com/stboch/homeassistant-blueprints/blob/203573805074ce9b5454a5e74d17c68c50573cf6/mobile_app_android_alarm.yaml
blueprint:
  name: Set Alarm for Samsung Devíces
  description: Set an alarm with help of the homeassistant companion app
  domain: script
  source_url: https://github.com/YoshiiPlayzz/homeassistant-extras/blob/main/blueprints/companion-android-set-alarm-samsung.yaml
  input:
    notify_device:
      name: Device to set the alarm to
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    command_choice:
      name: Command Choice
      description: Choose when alarm to trigger
      selector:
        time:
    skip_ui:
      name: Show UI
      description: A boolean specifying whether the responding app should skip its UI when setting the alarm. If true, the app should bypass any confirmation UI and simply set the specified alarm
      selector:
        boolean:
    vibrate:
      name: Vibrate
      description: A boolean specifying whether to vibrate for this alarm.
      selector:
        boolean:
    message:
      name: Message
      description: A custom message to identify the alarm.
      selector:
        text:           
mode: restart
variables:
  timeinput: !input command_choice
  message: !input message
  vibrate: !input vibrate
  skip_ui: !input skip_ui
sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    data:
      data:
        intent_package_name: "com.sec.android.app.clockpackage"
        intent_action: "android.intent.action.SET_ALARM"
        intent_extras: "android.intent.extra.alarm.HOUR:{{timeinput.split(":")[0]}},android.intent.extra.alarm.MINUTES:{{timeinput.split(":")[1]}},android.intent.extra.alarm.MESSAGE:{{message}},android.intent.extra.alarm.VIBRATE:{{vibrate}},android.intent.extra.alarm.SKIP_UI:{{skip_ui}}"
      message: "command_activity"